sudo: required
dist: trusty
os:
    - linux
language: python
python: 
  - "3.5"
# command to install dependencies
install:
  - bash install_ubuntu.sh
  - pip install tensorflow
  - pip install -U networkx matplotlib scikit-learn scipy spacy
  - python -m spacy download en
script:  
  - ls -la
  - cd src
  - ls -la
  - python main.py